# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: covid-page-update
on:
  push:
    branches: [ master ]
  schedule:
    - cron: 0 * * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6' # Version range or exact version of a Ruby version to use, using semvers version range syntax.
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Dependencies
      run: |
        pip install pandas
        pip install matplotlib
        pip install seaborn
    - name: What files are there now
      run: ls -la; pwd
    - name: Run daily
      run: erb index.erb.html > index.html
    - name: What files are there now
      run: ls -la; pwd
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
    - name: Push changes
      run: git add --all; git commit -m "funky"; git push
