# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: covid-page-update
on:
  push:
    branches: [  master ]
  schedule:
    - cron: 0 * * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Dependencies
      run: |
        pip install pandas
        pip install matplotlib
        pip install seaborn
    - name: Run daily
      run: erb index.erb.html > index.html
    - run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add --all; git commit -m "action"
        git push

